### ISSUE TITLE
 signature error

### ISSUE THREAD

**Issue by TsuNamiPlayZ** [bruhmoment21/csgo-imgui-sdk#1]
[INFO] VEngineClient014 => 0x171dd2dc
[INFO] InputSystemVersion001 => 0x5c2112a0
[INFO] VGUI_Surface031 => 0x501247c0
[INFO] IEffects001 => 0x2c27a250
[INFO] VClient018 => 0x3028dc40
[INFO] IEngineSoundClient003 => 0x1716b65c
[ERROR] 8B 3D ? ? ? ? 85 FF 74 1A is not a good signature!
[SUCCESS] Cheat has been unloaded successfully!

**Comment by bruhmoment21** [comment]
fixed. signatures::inventory_manager
