### ISSUE TITLE
lasa compilatorul sa determine marimea

### ISSUE THREAD

**Issue by cristeigabriel** [bruhmoment21/csgo-imgui-sdk#3]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/e45209bac580ab2579bc365a6cc583a415538c74/jet-sdk-csgo/src/signatures.cpp#L5

de cand cu C++ poti folosi template <size_t N> impreuna cu tip(&nume)[N] si asta va determina marimea arrayului automat

**Comment by cristeigabriel** [comment]
pe langa asta, recomand sa faci image cache,
snippet de code dintr-un proiect la care n-am platit multa atentie la cod clean:
```
#define expected_module_base 0x10000000
struct module_t
{
    module_t() = default;

    module_t(HMODULE _module)
    {
        if (!_module) {
            throw std::runtime_error("module is invalid");
        }

        m_module = _module;
        m_module_bitmap = (uint8_t*)m_module;
        m_module_dos_header = (PIMAGE_DOS_HEADER)m_module;
        m_module_base = m_module_dos_header->e_lfanew;
        if (m_module_base < expected_module_base) {
            printf("[warning] module base smaller than 0x%x\n", expected_module_base);
        }
        m_module_nt_headers = (PIMAGE_NT_HEADERS)(m_module + m_module_base);
        m_module_size = m_module_nt_headers->OptionalHeader.SizeOfImage;
        //  if ( module_as_bitmap != (struct_module_as_bitmap *)-1 && module_as_bitmap->e_magic == 23117 )
        m_module_is_x86 = (m_module_dos_header->e_magic == 23117);
        printf("[log] module is %s bit\n", m_module_is_x86 ? "x86" : "x64");
    }

    template<uint64_t N>
    uint8_t* pattern_scan(const int (&pattern)[N])
    {
        for (uint64_t i = 0; i < m_module_size - N; ++i) {
            bool proceed = true;
            for (uint64_t j = 0; j < N; ++j) {
                //  -1 = runtime information && in static analysis = skip
                if (m_module_bitmap[i + j] != pattern[j] && pattern[j] != -1) {
                    proceed = false;
                    break;
                }
            }

            if (proceed) {
                printf("[log] found pattern at %p in %p\n", &m_module_bitmap[i], m_module_bitmap);
                return &m_module_bitmap[i];
            }
        }

        throw std::runtime_error("failed in patternscan");
        return nullptr;
    }

  public:
    HMODULE           m_module;
    uint8_t*          m_module_bitmap;
    PIMAGE_DOS_HEADER m_module_dos_header;
    uint64_t          m_module_base;
    PIMAGE_NT_HEADERS m_module_nt_headers;
    uint64_t          m_module_size;
    bool              m_module_is_x86;
};
```

**Comment by cristeigabriel** [comment]
la punctul acesta insa, as muta scanningul extern, precum fac eu, si as folosi aritmetica intre pointeri cu diferentele de la base generate

**Comment by cristeigabriel** [comment]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/master/jet-sdk-csgo/src/signatures.cpp#L63

poti sa listezi patternul pur si simplu cu un stringstream, considerand ca nu il vei crea decat cand esuezi scanul

**Comment by cristeigabriel** [comment]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/master/jet-sdk-csgo/src/hooks.cpp#L75

poti folosi during_mouse/key code state aici

**Comment by cristeigabriel** [comment]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/master/jet-sdk-csgo/src/hooks.cpp#L69

muta try/catchingul in entrypoint doar

**Comment by cristeigabriel** [comment]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/master/jet-sdk-csgo/src/misc.cpp#L19

personal eu am aceasta utilitate pt bytepatching
```
    template<size_t N>
    void patch_at_address(std::ptrdiff_t addy, const int (&buffer)[N])
    {
        //  Old protection state
        DWORD new_protect, old_protect;

        //  Remove write protection
        if (!VirtualProtect(from_locus(addy), N, PAGE_EXECUTE_READWRITE, &new_protect)) {
            throw std::runtime_error("Failed making bytes writable");
            return;
        }

        //  Patch bytes
        memcpy(from_locus(addy), buffer, N);

        //  Restore old protection state
        if (!VirtualProtect(from_locus(addy), N, new_protect, &old_protect)) {
            throw std::runtime_error("Failed restoring bytes writability state");
            return;
        }
    }
```

nu folosesc template pt. addy deoarece am +100 adrese individuale care sunt folosite si tin consistenta.

**Comment by bruhmoment21** [comment]
multumesc m am uitat la tot ce ai scris am aproape tot si n am inteles la ce te ai referit aici:

> https://github.com/bruhmoment21/csgo-imgui-sdk/blob/master/jet-sdk-csgo/src/hooks.cpp#L75
> 
> poti folosi during_mouse/key code state aici

**Comment by cristeigabriel** [comment]
salut, ma refeream la faptulc a poti folosii functiile din inputinternal sa comunici cu wndprocul jocului, desi probabil ar necvesita niste schimbari (mici)

**Comment by cristeigabriel** [comment]
apropo ,felicitari pentru munca, frumos proiectul in comparatie cu primele iteratii

**Comment by bruhmoment21** [comment]
> apropo ,felicitari pentru munca, frumos proiectul in comparatie cu primele iteratii

multumesc. apreciez timpul acordat pe care l ai dat la aceste "flaws"!
