### ISSUE TITLE
Compiletime IDA Style signatures to Byte Arrays

### ISSUE THREAD

**Issue by cristeigabriel** [bruhmoment21/csgo-imgui-sdk#5]
https://github.com/bruhmoment21/csgo-imgui-sdk/blob/c35ab6965c36e696fc6a4fd5b204967d82508306/jet-sdk-csgo/src/signatures.cpp#L39

Am facut o utilitate care, exact in scenariul acesta, ajuta, prin a oferi posibilitatea de a folosii ida style signatures, si a le transforma in byte arrays precum folosesti tu, la compile time

https://github.com/cristeigabriel/compiletime-string-to-bytearray

exemplu de utiilizare:
```
template <int N>
constexpr int combine_two()
{
	constexpr auto numbers = stoba::make<"55 8B EC 83 E4 F8 8B 4D 08 BA ? ? ? ? E8 ? ? ? ? 85 C0 75 12 ?">();
	constexpr int number = numbers[0];
	constexpr int number_now = N + number;
	return number_now;
}
```

cred ca ti-ar placea, aceasta este doar o propunere de enhancement

**Comment by Aaliyah6022** [comment]
Sunt si eu incepator(ish), aveti discord? mi-ar place sa vorbesc cu voi

**Comment by cristeigabriel** [comment]
> Sunt si eu incepator(ish), aveti discord? mi-ar place sa vorbesc cu voi

para#1448 dar prefer tg in descriere git
